widget cinema added
pjehan/dc3-react-dashboard pull request #1
Opened 2017-11-08 17:11 UTC by valr13

Je viens de rajouter le widget cinéma, il n'est pas encore terminé. Je referais des pull request au fur et à mesure de l'avancement.

2017-11-08 17:55 UTC, pjehan requested changes
Super Valentin merci !
Cependant, il serait préférable de tout mettre dans un seul et même fichier. L'objectif serait au prochain cours de voir comment publier votre widget sur NPM pour que n'importe qui puisse le télécharger avec la commande npm install

2017-11-08 17:56 UTC, pjehan commented on public/index.html
> +    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
Est-ce que tu pourras définir la font comme paramètre du widget stp ? Comme ça, tu n'auras pas à l'inclure dans ton code et les utilisateurs de ton widget pourront la personnaliser.

2017-11-08 17:57 UTC, pjehan commented on src/index.css
> +
Déplace l'ensemble de ce code dans la constante "styles" de ton widget stp.

2017-11-08 17:58 UTC, pjehan commented on src/components/widgets/CinemaWidget.js
> +const styles = {
Il faudrait inclure le CSS que tu as écrit dans le fichier App.css pour que tout le code soit dans un seul fichier et qu'il soit ainsi plus facile à exporter / importer.

2017-11-08 18:01 UTC, pjehan commented on src/components/widgets/CinemaWidget.js
> +        const randomMovie = this.state.movies[Math.floor(Math.random() * this.state.movies.length)];
Ca serait pas mal de faire tourner les films un à un plutôt que de les sélectionner en random. Tu peux renommer la fonction getNextMovie puis ensuite avec un système d'incrémentation prendre le movie à l'index n + 1 jusqu'à la fin du tableau où tu retourneras à n = 0

2017-11-08 18:01 UTC, pjehan commented on src/components/widgets/CinemaWidget.js
> +            console.log(widgetOverview)
Peux-tu supprimer le console.log stp ?

2017-11-08 18:03 UTC, pjehan commented on src/components/widgets/CinemaWidget.js
> +                            <span className="CinemaWidget_releaseDate">{releaseDate.toLocaleDateString("fr-FR")}</span>
Si jamais tu souhaites afficher la date formatée, tu peux jeter un oeil à momentjs et l'installer via NPM. Quand tu mettra ton widget sur NPM ensuite, il ne faudra pas oublier d'ajouter momentjs dans la liste des dépendances dans le fichier package.json

2017-11-08 18:23 UTC, pjehan commented on src/components/widgets/CinemaWidget.js
> +        fetch('https://api.themoviedb.org/3/movie/now_playing?api_key=3d7cf719a2e58fdbbbdf2e3e18d283b3&language=fr-FR&page=1&region=FR')
Attention... il ne faut pas publier de clé API sur Github ! La clé API devrait être un paramètre du composant. Si tu fais des tests en modifiant le fichier App.js, tu peux ne pas le commiter par la suite. Fais simplement un git add src/components/widgets/CinemaWidget.js pour ajouter uniquement le code de ton composant.

2017-11-09 07:56 UTC, merged

2017-11-09 08:47 UTC, valr13 commented on public/index.html
> +    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
Je ne vois pas trop comment procéder pour définir la font comme paramètre ? A quel endroit dois-je l'importer ?

2017-11-09 09:58 UTC, pjehan commented on public/index.html
> +    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
La balise link restera bien dans le fichier index.html. Par contre, tu peux ajouter dans le state de ton component une propriété "font" qui sera définie dans le constructor : this.state= { font: this.props.font }